---
title: "SexDifferences"
author: "Jess Metcalf"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../..')
```

##Data Overview

```{r}
  fluscape.dat <- read.csv("data/HI_titers_paired_R56Pilot.csv")

  ##Create log titer variable
  tmp <- fluscape.dat$HI_Titer
  tmp[tmp==0] <- 5
  fluscape.dat$log_HI <- log2(tmp/5)
  
  ##Make a table of participants with their visit pairs
  require(dplyr)
  require(plyr)
  require(knitr)
  require(tidyr)
  tmp <- fluscape.dat[,c("Participant_ID","Visit")]
  tmp <- unique(tmp)
  visits.sum <- ddply(tmp,~Participant_ID, summarize, visits = paste(Visit, collapse="-"))
  kable(as.data.frame(table(visits.sum$visits)))

  ##reduce to those participants with V1-V4 data
  ids <- visits.sum$Participant_ID[visits.sum$visits=="V1-V4"]
  fluscape.dat.V1V4 <- fluscape.dat[which(fluscape.dat$Participant_ID%in%ids),]
   
  ##Now summarize so that duplicate titers are averaged.
  titers <- ddply(fluscape.dat.V1V4, ~Participant_ID+Virus+Visit, summarize, log_HI=mean(log_HI))
  
  ##Merge to create a better fluscape.dat data with only what is needed
  fluscape.dat.V1V4 <- 
    merge(fluscape.dat.V1V4[,c("Participant_ID","Visit","Virus","Location")],titers)
  fluscape.dat.V1V4 <- unique(fluscape.dat.V1V4)
  
  ##Make this so we have a visit 1 and visit 4 per viruses
  fluscape.dat.V1V4 <- spread(fluscape.dat.V1V4, Visit, log_HI)
  
  ##Get the differences
  fluscape.dat.V1V4$delta <- fluscape.dat.V1V4$V4 - fluscape.dat.V1V4$V1 
  
  ##get the strain years.
  yr <- as.numeric(substr(fluscape.dat.V1V4$Virus,start = 3,stop = 4))
  yr[fluscape.dat.V1V4$Virus=="X31"] <- 9999
  yr[yr<68] <- yr[yr<68] + 2000
  yr[yr<1000] <- yr[yr<1000] + 1900
  fluscape.dat.V1V4$Year <- yr

  ##look at differences by year
  boxplot(delta~Year, data=fluscape.dat.V1V4)
  
  require(ggplot2)
  ggplot(fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,], 
         aes(x=Year, y=delta)) +geom_point(alpha=0.01)+geom_smooth()
  
```
```{r}
source("source/R/GeneralUtility.R")
part.V1 <- load.and.merge.part.V1()

fluscape.dat.V1V4 <- merge(fluscape.dat.V1V4, part.V1[,c("Full.ID", "PART_AGE",
                                                         "PART_GENDER")], 
                           by.x="Participant_ID", by.y="Full.ID")

## make gender a factor
fluscape.dat.V1V4$PART_GENDER <- as.factor(fluscape.dat.V1V4$PART_GENDER)

## get seroconversion
fluscape.dat.V1V4$seroconvert <- fluscape.dat.V1V4$delta>=2

## get age at isolation for V4
fluscape.dat.V1V4$Age.At.Isolation <- fluscape.dat.V1V4$PART_AGE-
      (2014-fluscape.dat.V1V4$Year)

### get at age isolation for V1
fluscape.dat.V1V4$Age.At.Isolation.V1 <- fluscape.dat.V1V4$PART_AGE-
      (2009-fluscape.dat.V1V4$Year)

## get virus
fluscape.dat.V1V4$Virus <- as.factor(fluscape.dat.V1V4$Virus)

```

```{r}
## Plots of raw data / simple tests

## Make index of age (capturing puberty, menopause, ones you were too young to see)
IndexAge <- findInterval(fluscape.dat.V1V4$PART_AGE,c(0,13,30,60,100)) 
IndexAge <- as.factor(IndexAge)
levels(IndexAge) <- c("0-13 yrs","13-30 yrs","30-60 yrs", "60+ yrs")

## Make pretty index of sex
IndexSex <-  fluscape.dat.V1V4$PART_GENDER
levels(IndexSex) <- c("male","female")

## Use coplot
## shorten vectors to focal period
subst <- fluscape.dat.V1V4$Year<9999
#subst <- fluscape.dat.V1V4$Year<2004
#subst <- fluscape.dat.V1V4$Year<9999 & fluscape.dat.V1V4$Year>2004
IndexSexS <- IndexSex[subst]
IndexAgeS <- IndexAge[subst]

## not terribly clear
coplot(V4 ~ Year |IndexSexS * IndexAgeS, data = fluscape.dat.V1V4[subst,],
       show.given = 0:4,panel = panel.smooth)

## break years into <1990, 1990-2004, >2004
IndexYear <- findInterval(fluscape.dat.V1V4$Year,c(1960,1990,2004,2017)) 
IndexYear <- as.factor(IndexYear)
levels(IndexYear) <- c("<1990","1990-2004",">2004", "")

## sanity check the means
chs <-  fluscape.dat.V1V4$Year<1990 & fluscape.dat.V1V4$PART_AGE<13 & fluscape.dat.V1V4$V4>0
sapply(split(fluscape.dat.V1V4$V4[chs],fluscape.dat.V1V4$PART_GENDER[chs]),mean)

chs <-  fluscape.dat.V1V4$Year<1990 & fluscape.dat.V1V4$PART_AGE>13 & fluscape.dat.V1V4$V4>0
sapply(split(fluscape.dat.V1V4$V4[chs],fluscape.dat.V1V4$PART_GENDER[chs]),mean)


subst <- fluscape.dat.V1V4$Year==2009 & fluscape.dat.V1V4$V4>0
coplot(V4 ~ IndexSex[subst] | IndexAge[subst], data = fluscape.dat.V1V4[subst,],
       show.given = 0:4,panel = panel.smooth)

require(beeswarm)
require(vioplot)

par(mfrow=c(1,1), mar=c(10,5,3,3))
beeswarm(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst] * IndexAge[subst], xlab="", pch=19, corral="gutter", las=2, ylab="Titer")

u.age <- unique(IndexAge)
par(mfrow=c(2,4), mar=c(5,5,2,2))
for (j in 1:length(u.age)){
subst <- fluscape.dat.V1V4$Year==1968 & IndexAge==u.age[j]
vioplot(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="", ylab="Titer")
#beeswarm(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="", pch=1, corral="wrap", las=2, ylab="Titer")
title(u.age[j])
}
for (j in 1:length(u.age)){
subst <- fluscape.dat.V1V4$Year!=2009 & fluscape.dat.V1V4$Year<9999 & IndexAge==u.age[j]
vioplot(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="",  ylab="Titer")
#beeswarm(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="", pch=1, corral="wrap", las=2, ylab="Titer")
}


par(mfrow=c(2,4), mar=c(5,5,2,2))
for (j in 1:length(u.age)){
subst <- fluscape.dat.V1V4$Year==1968 & IndexAge==u.age[j]
vioplot(fluscape.dat.V1V4$V1[subst] ~ IndexSex[subst], xlab="", ylab="Titer")
#beeswarm(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="", pch=1, corral="wrap", las=2, ylab="Titer")
title(u.age[j])
}
for (j in 1:length(u.age)){
subst <- fluscape.dat.V1V4$Year==2014 & IndexAge==u.age[j]
vioplot(fluscape.dat.V1V4$V1[subst] ~ IndexSex[subst], xlab="",  ylab="Titer")
#beeswarm(fluscape.dat.V1V4$V4[subst] ~ IndexSex[subst], xlab="", pch=1, corral="wrap", las=2, ylab="Titer")
}


```




```{r}

### More plots to reveal differences between males and females

require(mgcv)

## get the average by age, virus and gender (don't remove the 0s since gets rids of male 0s to unobserved)
mean.V4 <- ddply(fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,], .(PART_AGE, PART_GENDER,Year), summarize,
  mean = mean(V4,na.rm=TRUE),
  sd = sd(V4,na.rm=TRUE))
## get the average grouping the sexes
mean.V4.both <- ddply(fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,], .(PART_AGE, Year), summarize,
  mean = mean(V4,na.rm=TRUE),
  sd = sd(V4,na.rm=TRUE))

## same for V1
mean.V1 <- ddply(fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,], .(PART_AGE, PART_GENDER,Year), summarize,
  mean = mean(V1,na.rm=TRUE),
  sd = sd(V1,na.rm=TRUE))
## get the average grouping the sexes
mean.V1.both <- ddply(fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,], .(PART_AGE, Year), summarize,
  mean = mean(V1,na.rm=TRUE),
  sd = sd(V1,na.rm=TRUE))


## Put these into matrices for comparison
test.age <- 2:86; test.virus.year <- unique(mean.V4$Year);
test.virus.year <- test.virus.year[order(test.virus.year)]

male.mean.mat <- female.mean.mat <- both.mean.mat <- male.mean.mat.1 <- female.mean.mat.1 <- both.mean.mat.1 <- matrix(NA,length(test.virus.year),86)
for (j in 1:length(test.virus.year)){
      tp <- mean.V4$Year==test.virus.year[j]  & mean.V4$PART_GENDER==1
      male.mean.mat[j,mean.V4[tp,"PART_AGE"]] <-  mean.V4[tp,"mean"]
      tp <- mean.V4$Year==test.virus.year[j]  & mean.V4$PART_GENDER==2
      female.mean.mat[j,mean.V4[tp,"PART_AGE"]] <-  mean.V4[tp,"mean"]
      tp <- mean.V4.both$Year==test.virus.year[j] 
      both.mean.mat[j,mean.V4.both[tp,"PART_AGE"]] <-  mean.V4.both[tp,"mean"]
      
      tp <- mean.V1$Year==test.virus.year[j]  & mean.V1$PART_GENDER==1
      male.mean.mat.1[j,mean.V1[tp,"PART_AGE"]] <-  mean.V1[tp,"mean"]
      tp <- mean.V1$Year==test.virus.year[j]  & mean.V1$PART_GENDER==2
      female.mean.mat.1[j,mean.V1[tp,"PART_AGE"]] <-  mean.V1[tp,"mean"]
      tp <- mean.V1.both$Year==test.virus.year[j] 
      both.mean.mat.1[j,mean.V1.both[tp,"PART_AGE"]] <-  mean.V1.both[tp,"mean"]
      
}

par(mfrow=c(1,3))

## plot out the titers for both sexs
cols1 <- colorRampPalette(c("grey","brown"))(50)
image(test.virus.year,1:86,as.matrix(both.mean.mat), xlab="", 
        ylab="Age", ylim=c(2,70), col=cols1)
points(test.virus.year,2014-test.virus.year,pch=19)

## plot out the sex differences
cols <- colorRampPalette(c("red","grey","blue"))(50)
image(test.virus.year,1:86,as.matrix(male.mean.mat-female.mean.mat), col=cols, zlim=c(-4,4), xlab="", ylab="Age", ylim=c(2,70))
#abline(a=30,b=-2, lty=3)
points(test.virus.year,2014-test.virus.year,pch=19)

## normalize each titer (subtract mean for each column); and replot the sex differences
male.mean.mat.adj <- (male.mean.mat-rowMeans(both.mean.mat,na.rm=TRUE)/apply(both.mean.mat,1,sd,na.rm=TRUE))
female.mean.mat.adj <- (female.mean.mat-rowMeans(both.mean.mat,na.rm=TRUE)/apply(both.mean.mat,1,sd,na.rm=TRUE))
image(test.virus.year,1:86,as.matrix(male.mean.mat.adj-female.mean.mat.adj), col=cols, zlim=c(-2,2), xlab="", ylab="Age", ylim=c(2,70))
#abline(a=30,b=-2, lty=3)
points(test.virus.year,2014-test.virus.year,pch=19)



## plot out the titers for both sexs
cols1 <- colorRampPalette(c("grey","brown"))(50)
image(test.virus.year,1:86,as.matrix(both.mean.mat.1), xlab="", 
        ylab="Age", ylim=c(2,70), col=cols1)
points(test.virus.year,2009-test.virus.year,pch=19)
abline(v=2009)

## plot out the sex differences
cols <- colorRampPalette(c("red","grey","blue"))(50)
image(test.virus.year,1:86,as.matrix(male.mean.mat.1-female.mean.mat.1), col=cols, zlim=c(-4,4), xlab="", ylab="Age", ylim=c(2,70))
#abline(a=30,b=-2, lty=3)
points(test.virus.year,2009-test.virus.year,pch=19)
abline(v=2009)




## plot out the sex differences for 2014, and 2009
par(mfrow=c(1,2), mar=c(5,5,2,2))
cols <- colorRampPalette(c("red","grey","blue"))(50)
image(test.virus.year,1:86,as.matrix(male.mean.mat.1-female.mean.mat.1), col=cols, zlim=c(-4,4), xlab="", ylab="Age", ylim=c(2,70))
#points(test.virus.year,2009-test.virus.year,pch=19)
abline(41+1968,-1)
abline(v=2009)

cols <- colorRampPalette(c("red","grey","blue"))(50)
image(test.virus.year,1:86,as.matrix(male.mean.mat-female.mean.mat), col=cols, zlim=c(-4,4), xlab="", ylab="Age", ylim=c(2,70))
#points(test.virus.year,2014-test.virus.year,pch=19)
abline(48+1968,-1)



```


```{r}
### TEST HYPOTHESIS 1: FEMALES HIGHER TITERS TO STRAINS THEY HAVE NEVER SEEN

## define strains never seen  (this is 2008?)
too.young <- fluscape.dat.V1V4$Age.At.Isolation <0 
too.young1 <- fluscape.dat.V1V4$Age.At.Isolation.V1 <0 

## plot out the young
chs <-  fluscape.dat.V1V4$PART_AGE<13 & too.young #& fluscape.dat.V1V4$V4>0
require(beeswarm)
par(mfrow=c(1,2), mar=c(10,4,1,1))
beeswarm(fluscape.dat.V1V4$V4[chs]~IndexSex[chs], xlab="", las=2, corral="gutter", col=c("blue","red"), pch=19,cex=0.2,ylab="")

chs <-  fluscape.dat.V1V4$PART_AGE>=13 & too.young #& fluscape.dat.V1V4$V4>0
beeswarm(fluscape.dat.V1V4$V4[chs]~IndexSex[chs], xlab="", las=2, corral="gutter", col=c("blue","red"), pch=19,cex=0.2,ylab="")


## not biased by females having more of the strains with high titers - evenly sampled
table(fluscape.dat.V1V4$Year[chs],IndexSex[chs])

## non parametric test not sig (bears out plot)
chs <-  too.young & fluscape.dat.V1V4$PART_AGE<13 #& fluscape.dat.V1V4$V4>0
w <- wilcox.test(fluscape.dat.V1V4$V4[chs]~IndexSex[chs])
w

## is sig for >age 13
chs <-  too.young & fluscape.dat.V1V4$PART_AGE>=13 #& fluscape.dat.V1V4$V4>0
w <- wilcox.test(fluscape.dat.V1V4$V4[chs]~IndexSex[chs])
w

par(mfrow=c(1,4), mar=c(10,4,1,1))
chs <-  fluscape.dat.V1V4$PART_AGE<13 & too.young #& fluscape.dat.V1V4$V4>0
vioplot(fluscape.dat.V1V4$V4[chs]~IndexSex[chs], xlab="", las=2,  col=c("lightblue","coral"), pch=19,cex=0.2,ylab="")

chs <-  fluscape.dat.V1V4$PART_AGE>=13 & too.young #& fluscape.dat.V1V4$V4>0
vioplot(fluscape.dat.V1V4$V4[chs]~IndexSex[chs], xlab="", las=2,  col=c("lightblue","coral"), pch=19,cex=0.2,ylab="")

chs <-  fluscape.dat.V1V4$PART_AGE<13 & too.young1 #& fluscape.dat.V1V4$V4>0
vioplot(fluscape.dat.V1V4$V1[chs]~IndexSex[chs], xlab="", las=2,  col=c("lightblue","coral"), pch=19,cex=0.2,ylab="")

chs <-  fluscape.dat.V1V4$PART_AGE>=13 & too.young1 #& fluscape.dat.V1V4$V4>0
vioplot(fluscape.dat.V1V4$V1[chs]~IndexSex[chs], xlab="", las=2,  col=c("lightblue","coral"), pch=19,cex=0.2,ylab="")




##### note no difference unless after puberty

## Make Figure 1 - include the differences, then look at too.young, all ages
par(mfrow=c(1,2))
par( mar=c(4,4,1,1))
cols <- colorRampPalette(c("red","grey","blue"))(50)
image(1:length(test.virus.year),1:86,as.matrix(male.mean.mat-female.mean.mat), col=cols, zlim=c(-4,4), xlab="", ylab="Age", ylim=c(2,70), axes=FALSE)
axis(2); axis(1,at=1:20,lab=rep("",20))
abline(a=30,b=-2, lty=3)
par( mar=c(8,2.5,1,0.5))

beeswarm(fluscape.dat.V1V4$V4[too.young& fluscape.dat.V1V4$PART_AGE>=13 & fluscape.dat.V1V4$V4>0]~IndexSex[too.young& fluscape.dat.V1V4$PART_AGE>=13 & fluscape.dat.V1V4$V4>0], xlab="", las=2, corral="gutter", col=c("blue","red"), pch=19,cex=0.2,ylab="")


```





```{r}

### Do full large model, all interactions, just to get a sense of the range, on raw titers, and looking at difference of smooths 
rawTiter.byYearSex <- gam(V4~s(PART_AGE,Year, by=PART_GENDER)+PART_GENDER, data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,])

## compare differences of smooths
yr.test <- unique(fluscape.dat.V1V4$Year)[1:19]
yr.test <- yr.test[order(yr.test)]
age.test <- seq(1,70,by=5)
pdat <- expand.grid(Year = yr.test,PART_AGE=age.test,PART_GENDER=c(1,2))
# basic function of the smooths at provided covariates
xp <- predict(rawTiter.byYearSex, newdata = pdat, type = 'lpmatrix')

## which cols of xp relate to splines of interest?
c1 <- grepl('PART_GENDER1', colnames(xp))
c2 <- grepl('PART_GENDER2', colnames(xp))
## which rows of xp relate to sexes of interest?
r1 <- with(pdat, PART_GENDER == 1)
r2 <- with(pdat, PART_GENDER == 2)

## difference rows of xp for data from comparison, doing male 
X <- xp[r1, ] - xp[r2, ]
## zero out cols of X related to splines for other lochs (in this case intercept)
X[, ! (c1 | c2)] <- 0
## zero out the parametric cols
X[, !grepl('^s\\(', colnames(xp))] <- 0

## get the difference; and the standard error of the difference
## putting them in a matrix
dif <- matrix(X %*% coef(rawTiter.byYearSex),length(yr.test),length(age.test))
se <- matrix(sqrt(rowSums((X %*% vcov(rawTiter.byYearSex)) * X)),length(yr.test),length(age.test)) 

## a point-wise 1 - α CI using the crit val of the t dist
crit <- qt(.975, df.residual(rawTiter.byYearSex))
upr <- dif + (crit * se)
lwr <- dif - (crit * se)

## plot out - negative = red means higher female
#cols <- colorRampPalette(c("red","white","blue"))(50)
#image(age.test,yr.test,t(dif), ylab="Year", xlab="Age", 
#      col=cols,zlim=c(-0.6,0.6))

## plot out in shape of antigenic seniority plot; bottom left corner 'unseen' females higher
## top right, suggesting females respond more strongly to contemporary
cols <- colorRampPalette(c("red","white","blue"))(50)
image(yr.test,age.test,dif, xlab="Year", ylab="Age", 
      col=cols,zlim=c(-0.6,0.6))
contour(yr.test,age.test,upr,level=0, lwd=2, add=TRUE)  # in these areas > 0
contour(yr.test,age.test,lwr,level=0, lwd=2, lty=3, add=TRUE) ## in these, less

## where is the data? basically everywhere....
##points(fluscape.dat.V1V4$Year,fluscape.dat.V1V4$PART_AGE, pch=19, cex=0.5)

##### things to consider = different years might hit very different levels (but no reason shouldn't be male and female)
```


```{r}
## look at the delta titer differences, same style
deltaTiter.byYearSex <- gam(delta~s(PART_AGE,Year, by=PART_GENDER)+PART_GENDER, data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999,])

## compare differences of smooths
yr.test <- unique(fluscape.dat.V1V4$Year)[1:19]
yr.test <- yr.test[order(yr.test)]
age.test <- seq(1,70,by=5)
pdat <- expand.grid(Year = yr.test,PART_AGE=age.test,PART_GENDER=c(1,2))
# basic function of the smooths at provided covariates
xp <- predict(deltaTiter.byYearSex, newdata = pdat, type = 'lpmatrix')

## which cols of xp relate to splines of interest?
c1 <- grepl('PART_GENDER1', colnames(xp))
c2 <- grepl('PART_GENDER2', colnames(xp))
## which rows of xp relate to sexes of interest?
r1 <- with(pdat, PART_GENDER == 1)
r2 <- with(pdat, PART_GENDER == 2)

## difference rows of xp for data from comparison, doing male 
X <- xp[r1, ] - xp[r2, ]
## zero out cols of X related to splines for other lochs (in this case intercept)
X[, ! (c1 | c2)] <- 0
## zero out the parametric cols
X[, !grepl('^s\\(', colnames(xp))] <- 0

## get the difference; and the standard error of the difference
## putting them in a matrix
dif <- matrix(X %*% coef(deltaTiter.byYearSex),length(yr.test),length(age.test))
se <- matrix(sqrt(rowSums((X %*% vcov(deltaTiter.byYearSex)) * X)),length(yr.test),length(age.test)) 

## a point-wise 1 - α CI using the crit val of the t dist
crit <- qt(.975, df.residual(deltaTiter.byYearSex))
upr <- dif + (crit * se)
lwr <- dif - (crit * se)

## plot out - negative = red means higher female
cols <- colorRampPalette(c("red","white","blue"))(50)
image(age.test,yr.test,t(dif), ylab="Year", xlab="Age", 
      col=cols,zlim=c(-0.6,0.6))

## plot out in shape of antigenic seniority plot; bottom left corner 'unseen' females higher
## top right, suggesting females respond more strongly to contemporary
cols <- colorRampPalette(c("red","white","blue"))(50)
image(yr.test,age.test,dif, xlab="Year", ylab="Age", 
      col=cols,zlim=c(-0.8,0.8))
contour(yr.test,age.test,upr,level=0, lwd=2, add=TRUE)  # in these areas > 0
contour(yr.test,age.test,lwr,level=0, lwd=2, lty=3, add=TRUE) ## in these, less


## plot


```




```{r}
## Break down by age and by delay to virus - much more temperate Justin style

## set up dummies
age.isolation.test <- -20:80
age.test <- 2:80
Virus.test <- unique(fluscape.dat.V1V4$Virus[fluscape.dat.V1V4$Year<9999])

### COMPARE A SET OF MODELS

## BASIC FLUSCAPE - then add gender
fit.0 <- gam(V4~s(PART_AGE)+s(Age.At.Isolation)+Virus, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<2009,])
fit.1 <- gam(V4~s(PART_AGE)+s(Age.At.Isolation)+Virus+PART_GENDER, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<2009,])
fit.2A <- gam(V4~s(PART_AGE,by=PART_GENDER)+s(Age.At.Isolation)+Virus+PART_GENDER, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<2009,])
fit.2B <- gam(V4~s(PART_AGE)+s(Age.At.Isolation,by=PART_GENDER)+Virus+PART_GENDER, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<2009,])
fit.3 <- gam(V4~s(PART_AGE,by=PART_GENDER)+s(Age.At.Isolation,by=PART_GENDER)+Virus+PART_GENDER, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<2009,])

## GET THE RELATIVE BICS/AICs/MSEs
bic <- c(BIC(fit.0),BIC(fit.1),BIC(fit.2A), BIC(fit.2B), BIC(fit.3))
aic <- c(AIC(fit.0),AIC(fit.1),AIC(fit.2A), AIC(fit.2B), AIC(fit.3))
mse <- c(mean(residuals.gam(fit.0,type="response")^2), mean(residuals.gam(fit.1,type="response")^2), 
         mean(residuals.gam(fit.2A,type="response")^2), mean(residuals.gam(fit.2B,type="response")^2),
         mean(residuals.gam(fit.3,type="response")^2))
bic-bic[1]
bic-bic[2]  #can't not include the intercept, so need for comparison to higher
aic-aic[1]
mse

## BIC SUGGESTS THAT NEED IT IN AGE.ISOLATION, BUT LITTLE GAINS OTHERWISE
par(mfrow=c(1,3)); plot(fit.2B)

## AIC likes both...
par(mfrow=c(1,4)); plot(fit.3)

## define the one you want
chs.model <- "fit.2B"
fit <- fit.2B

## FORMALLY EXTRACT THE UNCERTAINTY IN THE DIFFERENCE OFA CHOSEN MODEL
## compare differences of smooths
isolation.test <- unique(fluscape.dat.V1V4$Age.At.Isolation[fluscape.dat.V1V4$Year<9999])
isolation.test <- isolation.test[order(isolation.test)]
age.test <- seq(1,70,by=5)
vtest <- unique(fluscape.dat.V1V4$Virus[fluscape.dat.V1V4$Year<9999])
pdat <- expand.grid(Age.At.Isolation = isolation.test,PART_AGE=age.test,Virus=vtest[5],PART_GENDER=c(1,2))
# basic function of the smooths at provided covariates
if (chs.model=="fit.3") xp <- predict(fit.3, newdata = pdat, type = 'lpmatrix')
if (chs.model=="fit.2A") xp <- predict(fit.2A, newdata = pdat, type = 'lpmatrix') 
if (chs.model=="fit.2B") xp <- predict(fit.2B, newdata = pdat, type = 'lpmatrix') 

## which cols of xp relate to splines of interest?
c1 <- grepl('PART_GENDER1', colnames(xp))
c2 <- grepl('PART_GENDER2', colnames(xp))
## which rows of xp relate to sexes of interest?
r1 <- with(pdat, PART_GENDER == 1)
r2 <- with(pdat, PART_GENDER == 2)

## difference rows of xp for data from comparison, doing male 
X <- xp[r1, ] - xp[r2, ]
## zero out cols of X related to splines for other lochs (in this case intercept)
X[, ! (c1 | c2)] <- 0
## zero out the parametric cols
X[, !grepl('^s\\(', colnames(xp))] <- 0

## get the difference; and the standard error of the difference
## putting them in a matrix
if (chs.model=="fit.3") { 
  dif <- matrix(X %*% coef(fit.3),length(isolation.test),length(age.test))
  se <- matrix(sqrt(rowSums((X %*% vcov(fit.3)) * X)),length(isolation.test),length(age.test)) 
  pred.mean <- matrix(predict(fit.3, newdata = pdat),length(isolation.test),length(age.test))
  pred.se.mean <- matrix(predict(fit.3, newdata = pdat,se=TRUE)$se.fit,
                       length(isolation.test),length(age.test))}

if (chs.model=="fit.2A"){ 
## experiment
  dif <- matrix(X %*% coef(fit.2A),length(isolation.test),length(age.test))
  se <- matrix(sqrt(rowSums((X %*% vcov(fit.2A)) * X)),length(isolation.test),length(age.test)) 
  pred.mean <- matrix(predict(fit.2A, newdata = pdat),length(isolation.test),length(age.test))
  pred.se.mean <- matrix(predict(fit.2A, newdata = pdat,se=TRUE)$se.fit,
                         length(isolation.test),length(age.test))
}

if (chs.model=="fit.2B"){ 
## experiment
  dif <- matrix(X %*% coef(fit.2B),length(isolation.test),length(age.test))
  se <- matrix(sqrt(rowSums((X %*% vcov(fit.2B)) * X)),length(isolation.test),length(age.test)) 
  pred.mean <- matrix(predict(fit.2B, newdata = pdat),length(isolation.test),length(age.test))
  pred.se.mean <- matrix(predict(fit.2B, newdata = pdat,se=TRUE)$se.fit,
                         length(isolation.test),length(age.test))
}


## a point-wise 1 - α CI using the crit val of the t dist
crit <- qt(.975, df.residual(fit))
#crit <- qt(.975, df.residual(fit.2B))
upr <- dif + (crit * se)
lwr <- dif - (crit * se)

## plot out the difference and CIs
par(mfrow=c(3,1), mar=c(4,4,1,2))

plot(isolation.test,pred.mean[,chs.age], ylab="", 
     xlab="", type="l", xlim=c(-20,80), ylim=c(0,5))
points(isolation.test,pred.mean[,chs.age]-crit*pred.se.mean[,chs.age],type="l", lty=3)
points(isolation.test,pred.mean[,chs.age]+crit*pred.se.mean[,chs.age],type="l", lty=3)
#abline(h=0)
#par(mar=c(4,4,1,2))

chs.age <- 10  # no effect of age, or titer, so all the same. 
plot(isolation.test,dif[,chs.age], ylab="", 
     xlab="Age at isolation", type="l", ylim=c(-0.5,0.5), xlim=c(-20,80))
abline(h=0)
points(isolation.test,upr[,chs.age],type="l", lty=3)
points(isolation.test,lwr[,chs.age],type="l", lty=3)
text(0,0.45,"Larger male effect", pos=4)
text(0,-0.45,"Larger female effect", pos=4)

### and can do the same for age effect... but super wobbly. 
chs.isolation <- 50  #corresponds to the one that got you when you were ~ 7
plot(age.test,dif[chs.isolation,], ylab="", 
     xlab="Age in years", type="l", ylim=c(-0.6,0.6), xlim=c(1,60))
abline(h=0)
points(age.test,upr[chs.isolation,],type="l", lty=3)
points(age.test,lwr[chs.isolation,],type="l", lty=3)
text(0,0.5,"Larger male effect", pos=4)
text(0,-0.5,"Larger female effect", pos=4)



### plot for talk ##
par(mfrow=c(2,1), mar=c(4,4,1,2))

plot(isolation.test,pred.mean[,chs.age], ylab="", 
     xlab="", type="l", xlim=c(-20,70), ylim=c(0,6))
points(isolation.test,pred.mean[,chs.age]-crit*pred.se.mean[,chs.age],type="l", lty=3)
points(isolation.test,pred.mean[,chs.age]+crit*pred.se.mean[,chs.age],type="l", lty=3)
polygon(c(isolation.test,isolation.test[c(length(isolation.test),length(isolation.test):1)]),
        c(pred.mean[,chs.age]-crit*pred.se.mean[,chs.age], 
          pred.mean[c(length(isolation.test),length(isolation.test):1),chs.age]+
            crit*pred.se.mean[c(length(isolation.test),length(isolation.test):1),chs.age]), 
          col=grey(0.5,alpha=0.5), border="NA")


chs.age <- 10  # no effect of age, or titer, so all the same. 
plot(isolation.test,dif[,chs.age], ylab="", 
     xlab="Age at isolation", type="l", ylim=c(-0.5,0.5), xlim=c(-20,70))
abline(h=0)
points(isolation.test,upr[,chs.age],type="l", lty=3)
points(isolation.test,lwr[,chs.age],type="l", lty=3)
#text(0,0.45,"Larger male effect", pos=4)
#text(0,-0.45,"Larger female effect", pos=4)
polygon(c(isolation.test,isolation.test[c(length(isolation.test),length(isolation.test):1)]),
        c(upr[,chs.age],lwr[c(length(isolation.test),length(isolation.test):1),chs.age]),
           col=grey(0.5,alpha=0.5), border="NA")



```

```{r}

## see if pattern holds as remove each strain
rc.store <- matrix(NA,20,160)  #store for the projected for the missing
rc.age <- matrix(NA,20,80)

par(mfrow=c(4,5), mar=c(4,2,1,1))
for (v in 1:20) {
  fit.test <- gam(V4~s(PART_AGE)+s(Age.At.Isolation,by=PART_GENDER)+Virus+PART_GENDER, 
             data=fluscape.dat.V1V4[fluscape.dat.V1V4$Year<9999 &
                                      fluscape.dat.V1V4$Virus!=Virus.test[v],])
  chk <- 5; if (v==5) chk <- 6
  pdat <- expand.grid(Age.At.Isolation = isolation.test,
                      PART_AGE=age.test,Virus=vtest[chk],PART_GENDER=c(1,2))
  # basic function of the smooths at provided covariates
  xp <- predict(fit.test, newdata = pdat, type = 'lpmatrix')

  ## which cols of xp relate to splines of interest?
  c1 <- grepl('PART_GENDER1', colnames(xp))
  c2 <- grepl('PART_GENDER2', colnames(xp))
  ## which rows of xp relate to sexes of interest?
  r1 <- with(pdat, PART_GENDER == 1)
  r2 <- with(pdat, PART_GENDER == 2)

  ## difference rows of xp for data from comparison, doing male 
  X <- xp[r1, ] - xp[r2, ]
  X[, ! (c1 | c2)] <- 0
  X[, !grepl('^s\\(', colnames(xp))] <- 0

  ## get the difference; and the standard error of the difference
  dif <- matrix(X %*% coef(fit.test),length(isolation.test),length(age.test))
  se <- matrix(sqrt(rowSums((X %*% vcov(fit.test)) * X)),length(isolation.test),length(age.test)) 

  ## a point-wise 1 - α CI using the crit val of the t dist
  crit <- qt(.975, df.residual(fit.test))
  upr <- dif + (crit * se)
  lwr <- dif - (crit * se)

  ## plot out the difference and CIs
  chs.age <- 10  # no effect of age, or titer, so all the same. 
  plot(isolation.test,dif[,chs.age], ylab="", 
     xlab="Age at isolation", type="l", ylim=c(-0.5,0.5), xlim=c(-20,80))
  abline(h=0)
  points(isolation.test,upr[,chs.age],type="l", lty=3)
  points(isolation.test,lwr[,chs.age],type="l", lty=3)
  text(0,0.45,"Larger male effect", pos=4)
  text(0,-0.45,"Larger female effect", pos=4)
  
  ## predict values for the missing strain 
  ## (will inevitably be off by the mean, i.e., do relative to viral strain 5, or 6 if focal is 5)
  yr.isolation <- fluscape.dat.V1V4$Year[fluscape.dat.V1V4$Year<9999 &
                                      fluscape.dat.V1V4$Virus==Virus.test[v]][1]
  pdat1 <- expand.grid(Age.At.Isolation =(1:80)-(2014-yr.isolation) ,
                      PART_AGE=1,Virus=vtest[chk],PART_GENDER=c(1,2))
  # basic function of the smooths at provided covariates
  rc.store[v,] <- as.numeric(predict(fit.test, newdata = pdat1, type = 'response'))
  rc.age[v,] <- (1:80)-(2014-yr.isolation)
}


## Plot out observations for the missing - with crude mean adjustment
### plus also, this doesn't give much differences males and females
par(mfrow=c(4,5), mar=c(4,2,1,1))
for (v in 1:20){
  
   x <- fluscape.dat.V1V4$Age.At.Isolation[fluscape.dat.V1V4$Year<9999 &
                                      fluscape.dat.V1V4$Virus==Virus.test[v]]
   y <- fluscape.dat.V1V4$V4[fluscape.dat.V1V4$Year<9999 &
                                      fluscape.dat.V1V4$Virus==Virus.test[v]]
   cols <- as.numeric(fluscape.dat.V1V4$PART_GENDER[fluscape.dat.V1V4$Year<9999 &
                                      fluscape.dat.V1V4$Virus==Virus.test[v]])
   cols[cols==1] <- "lightblue"
   cols[cols==2] <- "coral"

   ##crude adjust mean
   adj <- mean(y)-mean(rc.store[v,])

   plot(rc.age[v,],rc.store[v,1:80]+adj, col=4, 
        ylim=range(y), type="n", xlab="Age at isolation", ylab="")
   points(x, y, cex=0.3, col=cols)
   points(rc.age[v,],rc.store[v,1:80]+adj, col=4, type="l")
   points(rc.age[v,],rc.store[v,81:160]+adj, col=2, type="l")
   
}

```

```{r}
##narrow in on seroconversion?
fluscape.dat.V1V4sc <- fluscape.dat.V1V4[fluscape.dat.V1V4$seroconvert==TRUE,]
## find titer after you've serocoverted
fit.sero <- gam(V4~s(PART_AGE,by=PART_GENDER)+s(Age.At.Isolation,by=PART_GENDER)+Virus+
                  PART_GENDER, data=fluscape.dat.V1V4sc[fluscape.dat.V1V4sc$Year<9999,])


## FORMALLY EXTRACT THE UNCERTAINTY IN THE DIFFERENCE OFA CHOSEN MODEL
## compare differences of smooths
isolation.test <- unique(fluscape.dat.V1V4sc$Age.At.Isolation[fluscape.dat.V1V4sc$Year<9999])
isolation.test <- isolation.test[order(isolation.test)]
age.test <- seq(1,70,by=5)
vtest <- unique(fluscape.dat.V1V4sc$Virus[fluscape.dat.V1V4sc$Year<9999])
pdat <- expand.grid(Age.At.Isolation = isolation.test,PART_AGE=age.test,Virus=vtest[5],PART_GENDER=c(1,2))
# basic function of the smooths at provided covariates
xp <- predict(fit.sero, newdata = pdat, type = 'lpmatrix')

## which cols of xp relate to splines of interest?
c1 <- grepl('PART_GENDER1', colnames(xp))
c2 <- grepl('PART_GENDER2', colnames(xp))
## which rows of xp relate to sexes of interest?
r1 <- with(pdat, PART_GENDER == 1)
r2 <- with(pdat, PART_GENDER == 2)

## difference rows of xp for data from comparison, doing male 
X <- xp[r1, ] - xp[r2, ]
## zero out cols of X related to splines for other lochs (in this case intercept)
X[, ! (c1 | c2)] <- 0
## zero out the parametric cols
X[, !grepl('^s\\(', colnames(xp))] <- 0

## get the difference; and the standard error of the difference
## putting them in a matrix
dif <- matrix(X %*% coef(fit.sero),length(isolation.test),length(age.test))
se <- matrix(sqrt(rowSums((X %*% vcov(fit.sero)) * X)),length(isolation.test),length(age.test)) 

## a point-wise 1 - α CI using the crit val of the t dist
crit <- qt(.975, df.residual(fit.sero))
upr <- dif + (crit * se)
lwr <- dif - (crit * se)

## plot out the difference and CIs
par(mfrow=c(1,2))
chs.age <- 10  # no effect of age, or titer, so all the same. 
plot(isolation.test,dif[,chs.age], ylab="", 
     xlab="Age at isolation", type="l", ylim=c(-0.5,0.5), xlim=c(-20,80))
abline(h=0)
points(isolation.test,upr[,chs.age],type="l", lty=3)
points(isolation.test,lwr[,chs.age],type="l", lty=3)
text(0,0.45,"Larger male effect", pos=4)
text(0,-0.45,"Larger female effect", pos=4)



### and can do the same for age effect... but super wobbly. 
chs.isolation <- 50  #corresponds to the one that got you when you were ~ 7
plot(age.test,dif[chs.isolation,], ylab="", 
     xlab="Age in years", type="l", ylim=c(-0.6,0.6), xlim=c(1,60))
abline(h=0)
points(age.test,upr[chs.isolation,],type="l", lty=3)
points(age.test,lwr[chs.isolation,],type="l", lty=3)
text(0,0.5,"Larger male effect", pos=4)
text(0,-0.5,"Larger female effect", pos=4)


```
